### PR TITLE
Adopt the new `MessageDef`s API

### PR DESCRIPTION
**Pull request by dpikhulya**
This PR does the following:
- Replaces remaining usages of Protobuf reflection with `MessageDef` API
- Replaces `KClass`-based message refs with `MessageDef`-based ones.
- Moves the `TimeExts.kt` file to the Chords Proto Values library where it should belong.

### CODE REVIEW

**Comment by armiol** [comment]
@dpikhulya is it still a draft?

**Comment by armiol** [comment]
@dpikhulya I am asking because GitHub told me the review was required.

**Comment by dpikhulya** [comment]
@armiol Yeah, it was a false alarm. I've found one more thing that needs to be addressed.

**Comment by dpikhulya** [comment]
@armiol Okay, addressed one more thing and it's ready for review now.

**Review by armiol — APPROVED** [review]

**Pull request merged**
